### ISSUE TITLE
AuthError.noSubject

### ISSUE THREAD

**Issue by jdmcd** [vapor/auth-example#1]
I am trying to create a login route. I have successfully created the register portion, but am struggling to determine what has gone wrong on the login side of things. 

I have the protect and auth middleware setup on the drop, as well as in the `middleware.json` file. Here is the code for my login route:

``` swift
users.post("login") { req in
        guard let username = req.data["username"]?.string else {
            throw Abort.badRequest
        }

        guard let password = req.data["password"]?.string else {
            throw Abort.badRequest
        }

        let creds = UsernamePassword(username: username, password: password)

        try req.auth.login(creds)

        let u = try req.user()

        return try JSON(node: ["message": "\(u.name) Logged in."])
    }
```

Which is all wrapped within a group called `users`.

Here's the weird thing. It always works the first time after clearing the cache, but then fails the second time (after succeeding the first time) and results in an error:

`Uncaught Error: AuthError.noSubject. Use middleware to catch this error and provide a better response. Otherwise, a 500 error page will be returned in the production environment.`

What am I doing wrong?? Here is my `authenticate` function on my `User` model:

``` swift
    static func authenticate(credentials: Credentials) throws -> Auth.User {
        let user: User?

        switch credentials {
        case let usernamePassword as UsernamePassword:
            print(usernamePassword.password + usernamePassword.username)
            user = try User.query().filter("email", usernamePassword.username).filter("password", usernamePassword.password).first()
        default:
            throw Abort.custom(status: .badRequest, message: "Invalid credentials.")
        }

        guard let u = user else {
            throw Abort.custom(status: .badRequest, message: "User not found")
        }

        return u
    }
```

**Comment by tanner0101** [comment]
`AuthError.noSubject` means that the `AuthMiddleware` isn't running before you're calling `req.user()`. Double check your routing and make sure you have the middleware added correctly.

**Comment by syky27** [comment]
Thanks @tannernelson it helped me 🎉
